project:
  type: book
  output-dir: docs

book:
  favicon: images/favicon.svg
  sidebar: 
    logo: images/logo-team-full-color.svg
    tools:
      - icon: github
        href: https://github.com/ryjohnson09/gapminder-analysis.git
      - icon: file-pdf
        href: https://drive.google.com/file/d/1AQqaVRl7S3PXOBh7in6RUfudykdvKMrh/view?usp=sharing
  chapters:
    - index.qmd
    
    - part: Overview and Setup
      chapters: 
        - workshop-access.qmd
        - download-project.qmd
        - configure-repos.qmd
        - api-keys.qmd
        - verify-publishing.qmd
    - part: Data
      chapters: 
        - rproj-restore.qmd
        - etl.qmd
    - part: Understand
    - part: Communicate
    - part: Bonus Content


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

